accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', views.landing, name='landing')
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    username = forms.CharField(label=("username"), widget=forms.PasswordInput(attrs={
        'class' : "form-control",
        'type' : "text",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))

    password1 = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={
        'class' : "form-control",
        'type' : "password",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        })
    )

    password2 = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={
        'class' : "form-control",
        'type' : "password",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        })
    )
    class Meta:
        model = User
        fields = ("username", "password1", "password2", )

class LoginForm(AuthenticationForm):
    username = forms.CharField(label=("username"), widget=forms.PasswordInput(attrs={
        'class' : "form-control",
        'type' : "text",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))

    password = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={
        'class' : "form-control",
        'type' : "password",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        })
    )
    class Meta:
        model = User
        fields = ("username", "password")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import SignupForm, LoginForm

def signup_view(request):
    form = SignupForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        user = form.save()
        username_login = request.POST['username']
        login(request, user )
        request.session['username'] = username_login
        return redirect('landing')
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username_login = request.POST['username']
            password_login = request.POST['password']
            user = authenticate(request, username=username_login, password=password_login)
            login(request, user)
            request.session['username'] = username_login
            return redirect('landing')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request :
        logout(request)
    return redirect('landing')

story9/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate

def landing(request):
    if request.user.is_authenticated :
        user = request.session.get('username')
    else :
        user = 'no name'
    return render(request, 'landing.html', {'user':user})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" id="but" value="signup">
    </form>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="signup" id="but">
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Hello!</title>
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <div class="row">
            <div class="col-sm">
                {% if 'username' in request.session %}
                <a href="{% url 'accounts:logout' %}" id="logout_button" class="btn btn-success m-1">logout</a>
            </div>
            <div class="col-sm">
                {% else %}
                <a href="{% url 'accounts:login' %}" id="login_button" class="btn btn-success m-1">login</a>
                <a href="{% url 'accounts:signup' %}" id="signup_button" class="btn btn-success m-1">signup</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="mx-auto isi">
        <h1 class="mt-4">Hello {{user}}</h1>
    </div>
</div>

{% endblock %}